language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - chmod +x gradlew
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t brightmask/frontend-docker:latest .
  - docker push brightmask/frontend-docker:latest

